
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ExpenseCategory = {
  Food: 'Food',
  Transportation: 'Transportation',
  Entertainment: 'Entertainment',
  Utilities: 'Utilities',
  Healthcare: 'Healthcare',
  Other: 'Other'
} as const

export type ExpenseCategory = (typeof ExpenseCategory)[keyof typeof ExpenseCategory]
